// auto-generated by Tetris_XH -- do not modify!
// any modifications should be made in cz.php

TETRIS_TX = {
    'utf-8-marker': 'äöüß',
    'syscheck_title': 'Kontrola systému',
    'syscheck_phpversion': 'PHP verze ≥ %s',
    'syscheck_extension': 'Rozšíření \'%s\' nahráno',
    'syscheck_encoding': 'Kódování \'UTF-8\' nastaveno',
    'syscheck_magic_quotes': 'magic_quotes_runtime off',
    'syscheck_jquery': '<a href=\"http://www.cmsimple-xh.com/wiki/doku.php/plugins:jquery4cmsimple\">jQuery4CMSimple plugin</a> instalován',
    'syscheck_writable': '\'%s\' zapisovatelné',
    'label_ok': 'Ok',
    'label_cancel': 'Zrušit',
    'label_play': 'Hraj',
    'label_highscores': 'Síň slávy',
    'label_rules': 'Pravidla',
    'label_about': 'O hře Tetris',
    'label_start': 'Start',
    'label_stop': 'Stop',
    'label_pause': 'Pauza',
    'label_resume': 'Pokračovat',
    'label_left': 'Vlevo',
    'label_right': 'Vpravo',
    'label_rotate': 'Otočit',
    'label_down': 'Dolů',
    'label_level': 'Úroveň',
    'label_rows': 'Počet řad',
    'label_score': 'Skóre',
    'message_howto_play': '<p> Jak hrát Tetris je vysvětleno na <a href=\'http://cs.wikipedia.org/wiki/Tetris\' target=\'_blank\'> Wikipedii </a>. </ p>Pro ovládání  použijte následující klávesy (pozor, šipky nefungují ve všech prohlížečích): </ p>',
    'message_about': '<p>Tetris pro CMSimple_XH.</p>',
    'error_no_js': 'Pro hru musí být ve vašem prohlížeči povolen javascript!'
};
