// auto-generated by Tetris_XH -- do not modify!
// any modifications should be made in en.php

TETRIS_TX = {
    'utf-8-marker': 'äöüß',
    'syscheck_title': 'System check',
    'syscheck_phpversion': 'PHP version &ge; %s',
    'syscheck_extension': 'Extension \'%s\' loaded',
    'syscheck_encoding': 'Encoding \'UTF-8\' configured',
    'syscheck_magic_quotes': 'magic_quotes_runtime off',
    'syscheck_jquery': '<a href=\"http://www.cmsimple-xh.com/wiki/doku.php/plugins:jquery4cmsimple\">jQuery4CMSimple plugin</a> installed',
    'syscheck_writable': '\'%s\' writable',
    'label_ok': 'Ok',
    'label_cancel': 'Cancel',
    'label_play': 'Play',
    'label_highscores': 'Highscores',
    'label_rules': 'Rules',
    'label_about': 'About &hellip;',
    'label_start': 'Start',
    'label_stop': 'Stop',
    'label_pause': 'Pause',
    'label_resume': 'Resume',
    'label_left': 'Left',
    'label_right': 'Right',
    'label_rotate': 'Rotate',
    'label_down': 'Down',
    'label_level': 'Level',
    'label_rows': 'Rows',
    'label_score': 'Score',
    'message_howto_play': '<p>How to play Tetris is explained at <a href=\'http://en.wikipedia.org/wiki/Tetris#Gameplay\' target=\'_blank\'>Wikipedia</a>.</p><p>Use the following keys (the arrow keys don\'t work in all browsers):</p>',
    'message_about': '<p>Tetris for CMSimple_XH.</p>',
    'error_no_js': 'Javascript must be enabled in your browser to play!'
};
